### ISSUE TITLE
New upstream repo

### ISSUE THREAD

**Issue by G-Ray** [flathub/org.gtk.Gtk3theme.Arc#1]
The new "upstream" repo seems to be https://github.com/NicoHood/arc-theme.

I can open a PR if you agree to use it ?

**Comment by G-Ray** [comment]
for reference: https://bugzilla.redhat.com/show_bug.cgi?id=1570058

**Comment by TingPing** [comment]
PR welcomed.

**Comment by TingPing** [comment]
Note that there are 6 repos on here for Arc variants.

**Comment by G-Ray** [comment]
@TingPing I updated the url, but the build is failing with flatpak-builder, because `inkscape` and `sass` are not found and there are not listed in the modules.

How can I test the build locally ?

**Comment by TingPing** [comment]
Well those must be new dependencies, that sucks since you'll need to add them to the modules. Might be best to switch to binary packages instead  of source.

**Comment by jurf** [comment]
It _might_ be able to use librsvg instead of Inkscape with some small patching, but not entirely sure about that. Could be worth a try though.

**Comment by jnsh** [comment]
The Arc-Theme repo that I'm maintaining at https://github.com/jnsh/arc-theme will drop the `inkscape` dependency for future releases with https://github.com/jnsh/arc-theme/commit/3421f0ec49b4d16521a536ecf643039b764e4ddd (`inkscape` is still required when building from a git snapshot).

@TingPing Is there still anything else problematic for updating the Flathub package? From now on the remaining build dependencies are `meson`, `sassc` and `glib-compile-resources`.

**Comment by TingPing** [comment]
@jnsh Oh that change sounds perfect. I'll try to get around to updating these ~~this week~~ when you make a release.

**Comment by jnsh** [comment]
@TingPing Great! If the remaining dependencies are fine, I'll roll out a new release later this week.

**Comment by TingPing** [comment]
Yeah, none of those deps are problematic.

**Comment by jnsh** [comment]
I have published Arc-theme version [20220102](https://github.com/jnsh/arc-theme/releases/tag/20220102), with the aforementioned dependency updates.

Worth mentioning is the Arc-Lighter variant that's been added since forking from the original repository by @horst3180. There has been some request for adding it as a Flatpak package.

Also, there is now Arc GTK4 theme available, which may be worth adding to Flathub as well?

Let me know if you have any further Flathub/Flatpak specific requests. For example, I've been wondering if [this](https://github.com/arc-design/arc-theme/issues/163) might be useful for versioned GTK4 themes?

**Comment by TingPing** [comment]
@jnsh I have updated all variants, I have added a -Lighter variant.

Currently there isn't a solution for GTK4 themes as that requires a bit of runtime changes.

**Comment by TingPing** [comment]
> For example, I've been wondering if this might be useful for versioned GTK4 themes?

Versioned directories doesn't really help flatpak but I think a build option would be fine.

I'd expect GTK4 to change theme API far less, if at all, than GTK3 did. So this might not be a real problem anymore. It was more of an issue with the 3.18 -> 3.20 transition.

**Comment by jnsh** [comment]
@TingPing Thank you for updating the packages, and your feedback.

I'll try to figure out best solution for GTK4, but good to know it doesn't matter for Flatpak.
